### PR TITLE
Double editor on one page error

### PR DESCRIPTION
**Pull request by garrensmith**
Hey,

Thanks for a great lib, I'm getting a `Uncaught Error: NOT_FOUND_ERR: DOM Exception 8` when I try to use two editors on one page. I've edited the index to show the error. I'm using the latest chrome.

After about 2 hours of hunting the bug I found it on line 191 of `bootstrap-wysihtml5.js`:

```
toolbar.append(options.toolbar[key]);
```

I cant quite figure out what this line is doing and why its causing that error. Sorry I'm not more helpful. Let me know if I can help more.

### CODE REVIEW

**Comment by Bratzilla** [comment]
I can confirm that you are correct. I commented about this exact issue in an earlier thread.

**Comment by blocka** [comment]
+1 Just got bit with this one as well.

**Comment by edslocomb** [comment]
I believe this should be fixed in #95

**Comment by jhollingworth** [comment]
@edslocomb fixed this in #95, thanks!

**Comment by garrensmith** [comment]
Brilliant, thanks.

**Pull request closed without merging**
