### PR TITLE
Add align options (Commands justifyCenter, justifyLeft, justifyRight)

### PR DESCRIPTION
**Pull request by jque**

### CODE REVIEW

**Comment by thet** [comment]
@jque why did you close this pull request? seems quite useful to me

**Comment by jque** [comment]
because it is not accepted

**Comment by thet** [comment]
oh.
but after studying the source code, i can see that a customTemplates option is accepted. this way and with the other config options, it's possible to inject your additions to bootstrap-wysihtml5

**Comment by thet** [comment]
for reference: i did an integration of what you've done with the parsing rules for a yafowil (a python form library) widget like so:

https://github.com/bluedynamics/yafowil.widget.wysihtml5/blob/master/src/yafowil/widget/wysihtml5/resources/widget.js

it extends the bootstrap-wysihtml5 editor with the justify toolbar and parsing rules (among a lot other things).

**Comment by jque** [comment]
Good job

**Pull request closed without merging**
