### PR TITLE
Added missing strings in es-ES, es-AR, de-DE

### PR DESCRIPTION
**Pull request by cheiff**
Hi,
just added a couple of missing strings in these translations.
This time for real... tested and working fine.
Thanks.

### CODE REVIEW

**Comment by Waxolunist** [comment]
Since this repo is dead, would you mind to make the PR into my still maintained repo over here: https://github.com/Waxolunist/bootstrap3-wysihtml5-bower

**Comment by cheiff** [comment]
how do I do that? If I try to fork it from your repo it takes me back to the original.
Thanks

**Comment by Waxolunist** [comment]
You can of course fork my repo like any other repo. Clone it, create a branch, copy your files over and make a pull request.

**Comment by cheiff** [comment]
Done.
Regards

**Comment by Waxolunist** [comment]
thx

**Pull request closed without merging**
