### PR TITLE
Add images list to images input window

### PR DESCRIPTION
**Pull request by Asherlc**
First pull request ever, so go easy on me, but I added the ability to specify a JSON URL, which then populates a list of image URL's in the image input window. I think this makes it a lot easier to use in many cases, where there is a list of files elsewhere.

### CODE REVIEW

**Comment by sams** [comment]
its interesting but seems to need some tweaking.  Would be nice to add an example of use.  I have got it partially working but no image is insert I get this error below:

`
Uncaught Error: INVALID_NODE_TYPE_ERR: DOM Range Exception 2 wysihtml5-0.3.0.js:2240
createBeforeAfterNodeSetter wysihtml5-0.3.0.js:2240
wysihtml5.Selection.Base.extend.setAfter wysihtml5-0.3.0.js:5976
wysihtml5.commands.insertImage.exec wysihtml5-0.3.0.js:7419
wysihtml5.Commands.Base.extend.exec wysihtml5-0.3.0.js:6792
Wysihtml5.initInsertImage.insertImage bootstrap-wysihtml5-0.0.2.js:246
f.event.dispatch jquery-1.7.2.min.js:3
f.event.add.h.handle.i
`

Also it would be good to be able to reload the assetUrl (I can't get it to use ./images.json instead it always loads /assets.json) - I think that support for thumbs should be added too.  Something similar could  be done with links also

**Comment by Asherlc** [comment]
Hm, I think I forgot to update the `dist` file to the most recent version -- I've pushed up the changes (though I didn't apply it to the minified version). It's not giving me that error using the sample page, though I'm having trouble getting GitHub pages to work to test (AJAX loading locally seems to be a problem). Is it working better for you now?

**Comment by Asherlc** [comment]
Ah, I spoke too soon. The JSON sample file had an error in it. I've corrected it and pushed - the index.html sample page now works fine for me.

**Comment by Asherlc** [comment]
Forgive me if I'm misunderstanding, but those seem like issues outside the scope of this pull request. Are they specific to the images listing?

**Comment by Asherlc** [comment]
I've made some more changes that I think will be pretty useful. The most notable is that now there's an ajax file upload field right in the image insert modal, making it much easier to add images on the fly.

I do have a couple problems I'm encountering, if anyone has any suggestions I'd be very appreciative:
- The `initImageUpload();` function is currently whenever the image modal is clicked. This doesn't really work since that means the function is initiated several times. However, when I add it elsewhere, it seems to get called before the modal is ready, so it never is able to get the DOM object.
- the `imagesUrl` default value isn't getting overridden by the instantiation options.
- I'm getting the `Uncaught Error: INVALID_NODE_TYPE_ERR: DOM Range Exception 2` sporadically. I'm not able to make it appear consistently.

I'm afraid I'm a bit stumped by these problems, so if anyone has ideas, that'd be great. Thanks!

**Comment by sams** [comment]
move the getimages below the following block
`
if(options[key] !== undefined) {
                    if(options[key] === true) {
                        value = true;
                    }
                } else {
                    value = defaultOptions[key];
                }`

and check if string (it should not be enabled by default)

`if(key === 'imagesUrl' && typeof options[key] === 'string') {
    this.getImages(options[key]);
}
`

imageUpload should be handled by another script (not bootstrap-wysihtml5 IMHO)
I have made some progress with using callbacks here

if these props are enabled the tab menu would have nav items set (for the extra options upload and list)

I am working towards thumbnails, delete links being optional in image list.

Using ids could cause problems with multiple editors.

**Comment by Asherlc** [comment]
Thanks! I'll try that out this evening.

The callback for image uploading sounds like a good idea, as well as the tab menu enabling.

For the callback, how much do you think should be set up in advance in the template? It needs an iframe in there to do the "ajax" upload, so that could either be in the template, or created on the fly with jquery in the callback.

I'll also work on removing the ID's, and replacing with $.find() methods. One thing is that the iFrame is targeted by the form using the iframe's name attribute, so if people are instantiating multiple wysiwigs on a page using one jquery selector, it might be difficult to make that work.

Looking forward to seeing what you come up with re: thumbnails and delete links.

**Comment by Asherlc** [comment]
I've worked in @sams edits and suggestions. I've also included what I think is likely to be the most common upload callback function into the sample html.

I'm still getting the `Uncaught Error: INVALID_NODE_TYPE_ERR: DOM Range Exception 2` error, but that seems to be related to issue #138, so I don't think it's a function of the additions.

**Comment by sams** [comment]
nice :) I don't get that error.

UPDATE: I have merged a bunch of PRs into a [develop](https://github.com/sams/bootstrap-wysihtml5/commits/develop) branch which I have just pushed

Plan to add a set of examples in a dir to demo these updates & to add my ideas to this branch
@Asherlc you may want to have a look at that branch.

**Pull request closed without merging**
