### PR TITLE
Internationalization Support

### PR DESCRIPTION
**Pull request by volmer**
I've added a basic internationalization support to bootstrap-wysihtml5, by replacing the static string in toolbar into locale specific ones. This way, a new option "locale" can be passed to the `wysihtm5()` method in order to translate it.

Example (translate to Brazilian Portuguese):

``` html
<script src="src/locales/bootstrap-wysihtml5.pt-BR.js"></script>
```

``` javascript
$('#some-textarea').wysihtml5({locale: "pt-BR"});
```

The default is English ("en") if no locale option is given. I've added the Brazilian Portuguese translation as well. Other translations may be added in the `src/locales` directory.

Please let me known if something went wrong :)

### CODE REVIEW

**Comment by frahugo** [comment]
Nice.  I wanted to do something similar.  Once merged, I'll submit a French version.

**Comment by volmer** [comment]
That would be great, @frahugo !

**Comment by leehambley** [comment]
This looks like a great avenue of work, I need to present wysihtml5 to my clients in German, this would be great!

**Comment by kszucs** [comment]
``` javascript
/**
 * Hungarian translation for bootstrap-wysihtml5
 */
(function($){
    $.fn.wysihtml5.locale["hu-HU"] = {
        font_styles: {
              normal: "Normál",
              h1: "Címsor 1",
              h2: "Címsor 2"
        },
        emphasis: {
              bold: "Félkövér",
              italic: "Dőlt",
              underline: "Aláhúzott"
        },
        lists: {
              unordered: "Rendezetlen lista",
              ordered: "Rendezett lista",
              outdent: "Kihúzás",
              indent: "Behúzás"
        },
        link: {
              insert: "Link beszúrása",
              cancel: "Mégsem"
        },
        image: {
              insert: "Kép beszúrása",
              cancel: "Mégsem"
        },
        html: {
            edit: "HTML szerkesztése"
        }
    };
}(jQuery));
```

**Comment by volmer** [comment]
Nice job, @threestan ! :+1:

**Comment by justgo** [comment]
``` javascript
/**
* Turkish translation for bootstrap-wysihtml5
* Emrah ÇELİK / JustGo
**/

(function($){
    $.fn.wysihtml5.locale["tr-TR"] = {
        font_styles: {
              normal: "Normal metin",
              h1: "Başlık 1",
              h2: "Başlık 2"
        },
        emphasis: {
              bold: "Kalın",
              italic: "İtalik",
              underline: "Altı Çizili"
        },
        lists: {
              unordered: "Liste",
              ordered: "Liste Numaralı",
              outdent: "Çıkıntı",
              indent: "Girinti"
        },
        link: {
              insert: "Bağlantı Ekle",
              cancel: "İptal"
        },
        image: {
              insert: "Resim Ekle",
              cancel: "İptal"
        },
        html: {
            edit: "HTML Düzenle"
        }
    };
}(jQuery));
```

**Comment by volmer** [comment]
Excellent, @justgo ! 
@robashton , could you please take a look at this pull request?

**Comment by robashton** [comment]
I haven't got write access - but I sit next to @jhollingworth at work so I'll review the commits and beat him over the head with a stick until it is merged.

**Comment by robashton** [comment]
Looks sensible, I'll commence the beating.

**Comment by jhollingworth** [comment]
OW

**Comment by serialseb** [comment]
I know the PR is closed n all. But the language should default in the default language for the current document shouldnt it? Also, in xhtml you'd have to find the current xhtml:lang, and in html5 it'd be the lang.

**Comment by jhollingworth** [comment]
@serialseb sounds like a sensible addition. I will try and have a look at some point unless you want to send a pull request? :) Also, any chance you could do a French translation?

**Pull request merged**
